version: '3'

services:
  app-develop:
    image: cc-backend/headless
    build:
      context: ../..
      dockerfile: ./docker/headless/Dockerfile
      args:
        - GOLANG_VERSION=${CC_BACKEND_ROOT_CONSOLE_GOLANG_VERSION}
        - ALPINE_VERSION=${CC_BACKEND_ROOT_CONSOLE_ALPINE_VERSION}
    volumes:
      - ../..:/code